#!/usr/bin/env python
import sys
import pyrax

nm = sys.argv[1]
pw = sys.argv[3]
dbname = sys.argv[2]

pyrax.set_setting("identity_type", "rackspace")
pyrax.set_credentials("USER", "APIKEY")


cdb = pyrax.cloud_databases

instances = cdb.list()
inst = instances[0]
db = inst.create_database(dbname)

user = inst.create_user(nm, pw, database_names=dbname)
