#!/usr/bin/env python
import pyrax
import os
pyrax.set_setting("identity_type", "rackspace")
pyrax.set_credentials("USER", "APIKEY")

cs = pyrax.cloudservers

os.system("cat /root/rs-scripts/newserverlist1.txt > thelist")
os.system("cp /root/rs-scripts/newserverlist2.txt /root/rs-scripts/tmpserver")


servers = cs.servers.list()
for server in servers:
        networks = server.networks["public"]
        for public_ip in networks:
                if '.' in public_ip:
                        if 'MAINSERVERIP' not in public_ip:
                                fuckip = public_ip
                                print(fuckip)
                                cmd="sed -i 's/XXX.XXX.XXX.XXX/"+fuckip+"/g' /root/rs-scripts/tmpserver"
                                os.system(cmd)
                                os.system("cat /root/rs-scripts/tmpserver >> thelist")

os.system("cp /root/rs-scripts/thelist /etc/lsyncd.lua")
os.system("service lsyncd restart")
